### ISSUE TITLE
@axunonb Sorry for the late response.  I looked over the solution.  I think that'll work in my case.

### ISSUE THREAD

**Issue by Payaspx** [axuno/VirtualFileSystem#1]
Master  Sorry for the late response.  I looked over the solution.  I think that'll work in my case.

I'm not sure if the extension method would make sense because I don't know how other people are using the utility.  For me, the biggest draw is the fact that I can set the string format at runtime as oppose to compile time.  With my usage of the utility I'll be pulling the format from a data store so the extension method would not help me in that case.

_Originally posted by @rich-ng in https://github.com/axuno/SmartFormat/issues/131#issuecomment-876522276_

**Comment by axunonb** [comment]
Doesn't belong to this repo
